<!DOCTYPE html>
<html lang="en">
<head>
    <title>Calvin Loveland</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<body>
<div id="main">

    <?php include("header.html"); ?>
    <div id="title">
        <img id="profile" src="me_irl.jpg"/>
        <span class="title-line" style="text-decoration: underline;">Calvin Loveland</span>
        <hr style="width:75%; color: #0e1717;">
        <p>I am a Computer Science sophomore at Utah State University</p>
        <p>I'm experienced in: </p>
        <script type="text/javascript"> C++, C#, Bicycle Maintenance, Java, HTML, CSS, Computer Hardware, PHP, Python, Cooking
        <p> JQuery, Car Maintenance,  </script>

    </div>
</body>

</div>
</html>